default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:
  password:

development:
  <<: *default
  database: cran-indexer_development

test:
  <<: *default
  database: cran-indexer_test

production:
  <<: *default
  database: cran-indexer_production
  username:
  password:
